version: 0.0
os: linux
files:
  - source: /main.py
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: env_create.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 300
      runas: root